# This workflow will build a Java project with Maven 
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
    paths:
      - 'apis/user-java/**'
      - '.github/workflows/api_user-java.yml'
 
  pull_request:
    branches: [ master ]
    paths:
      - 'apis/user-java/**'
      - '.github/workflows/api_user-java.yml'
    
  
defaults:
  run:
    working-directory: apis/user-java/

jobs:
  test_and_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Clean with Maven
      run: mvn clean
    - name: Test with Maven
      run: mvn test
    - name: Install with Maven
      run: mvn install
    - name: Create an issue on push       
      uses: JasonEtco/create-an-issue@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
